(function(){
  "use strict";
  const SUPABASE_URL="https://uajqwyoqbbswkfiwosyw.supabase.co";
  const SUPABASE_ANON_KEY="sb_publishable_hfiuO4ZRn4VZmEkrN2RV-A_lZX_R3z7";
  const SHORTLIST_KEY="smv_venue_shortlist_v2",COMPARE_KEY="smv_venue_compare_v2";
  const client=window.supabase?.createClient(SUPABASE_URL,SUPABASE_ANON_KEY,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});
  const grid=document.getElementById("venueGrid"),shell=document.querySelector(".venue-filter-shell"),params=new URLSearchParams(location.search);
  let venues=[],shortlist=readIds(SHORTLIST_KEY),compare=readIds(COMPARE_KEY).slice(0,3);
  const state={q:String(params.get("q")||"").trim().toLowerCase(),city:String(params.get("city")||params.get("location")||"").trim(),type:String(params.get("type")||"").trim(),location:"",food:"",occasion:String(params.get("occasion")||"").trim(),capacity:String(params.get("capacity")||"").trim(),budget:String(params.get("budget")||"").trim(),more:"",sort:"recommended"};
  const clean=v=>String(v==null?"":v).trim(),normal=v=>clean(v).toLowerCase(),escapeHtml=v=>String(v??"").replace(/[&<>'\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'\"':"&quot;"})[c]);
  const safeUrl=v=>{try{const u=new URL(String(v||""));return["http:","https:"].includes(u.protocol)?u.href:""}catch(_){return""}};
  const publicLocation=v=>{try{if(window.SMVPublicDetails&&typeof window.SMVPublicDetails.location==="function")return window.SMVPublicDetails.location(v)}catch(_){}const area=clean(v&&v.area),city=clean(v&&v.city),parts=area.split(",").map(clean).filter(Boolean);if(city&&!parts.some(x=>normal(x)===normal(city)||normal(x)===normal("New "+city)))parts.push(city);return [...new Set(parts)].join(", ")||"Location on request"};
  const eventTypes=v=>{const raw=v.event_types||v.events||v.suitable_events||[];return Array.isArray(raw)?raw.map(String).map(clean).filter(Boolean):String(raw||"").split(/[,|]/).map(clean).filter(Boolean)};
  const money=v=>!v?null:new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(Number(v));
  const capacityText=v=>{const a=Number(v.capacity_min||0),b=Number(v.capacity_max||0);return a&&b?`${a}–${b} guests`:b?`Up to ${b} guests`:a?`${a}+ guests`:"On request"};
  const priceText=v=>{const a=money(v.price_min_per_person),b=money(v.price_max_per_person);return a&&b?`${a}–${b}/person`:a?`${a}+/person`:b?`Up to ${b}/person`:"Quote on request"};
  const features=v=>{const a=[];if(v.food_veg)a.push("Vegetarian");if(v.food_non_veg)a.push("Non-Vegetarian");if(v.parking_available)a.push("Parking");if(v.rooms_available)a.push("Rooms");if(v.catering_available)a.push("Catering");if(v.decoration_available)a.push("Decoration");return a};
  const track=(name,details={})=>{try{window.dataLayer=window.dataLayer||[];if(typeof window.gtag==="function")window.gtag("event",name,details);else window.dataLayer.push({event:name,...details})}catch(_){}};
  const activeNeeds=()=>[
    state.city||state.location?`location: ${state.location||state.city}`:"",
    state.type?`venue type: ${state.type}`:"",
    state.occasion?`occasion: ${state.occasion}`:"",
    state.capacity?`capacity: ${state.capacity}`:"",
    state.budget?`budget: ${state.budget}`:"",
    state.food?`food: ${state.food}`:"",
    state.more?`facility: ${state.more}`:""
  ].filter(Boolean);
  const fitMessage=()=>{const needs=activeNeeds();return needs.length?`Matches ${needs.slice(0,3).join(" · ")}${needs.length>3?` · +${needs.length-3} more`:""}`:"Verified details published by the venue"};
  function readIds(k){try{const x=JSON.parse(localStorage.getItem(k)||"[]");return Array.isArray(x)?x.map(String):[]}catch(_){return[]}}
  function saveIds(k,x){try{localStorage.setItem(k,JSON.stringify(x))}catch(_){}}
  function capBucket(n){if(n<50)return"Less than 50";if(n<100)return"50–99";if(n<200)return"100–199";if(n<300)return"200–299";if(n<500)return"300–499";if(n<700)return"500–699";if(n<1000)return"700–999";return"1000+"}
  const CAPACITY_ORDER=["Less than 50","50–99","100–199","200–299","300–499","500–699","700–999","1000+"];
  const BUDGET_ORDER=["Up to ₹1,000","₹1,001–1,500","₹1,501–2,000","₹2,001–3,000","₹3,000+"];

  function installStyles(){
    if(document.getElementById("smvBrowsePremiumFilters"))return;
    const s=document.createElement("style");s.id="smvBrowsePremiumFilters";s.textContent=`
      .smv-browse-top{position:relative;z-index:20;border-bottom:1px solid rgba(93,223,204,.16);background:linear-gradient(100deg,#062d29,#0b4a42 55%,#062d29);box-shadow:0 10px 28px rgba(0,0,0,.18)}
      .smv-browse-top-inner{width:min(1460px,calc(100% - 34px));margin:auto;display:grid;grid-template-columns:220px minmax(0,1fr) 165px 165px;gap:10px;padding:10px 0}.smv-browse-top select,.smv-browse-top input{min-height:45px;width:100%;border:1px solid rgba(109,231,211,.23);border-radius:11px;background:#073b35;color:#effffb;padding:0 12px;font:inherit;font-size:13px;font-weight:800;outline:none}.smv-browse-top input::placeholder{color:#8db7af}.smv-browse-top button{min-height:45px;border:1px solid rgba(240,205,112,.4);border-radius:11px;background:linear-gradient(135deg,#f3d984,#c69a36);color:#17382f;font:inherit;font-size:11.5px;font-weight:950;cursor:pointer}
      .smv-browse-marquee{overflow:hidden;border-bottom:1px solid rgba(243,204,91,.22);background:linear-gradient(90deg,#031d1a,#092f2b,#031d1a);color:#f5d77c;white-space:nowrap}.smv-browse-marquee-track{display:inline-block;min-width:200%;padding:7px 0;font-size:10.5px;font-weight:900;letter-spacing:.08em;text-transform:uppercase;animation:smvBrowseTicker 24s linear infinite}.smv-browse-marquee-track span{display:inline-block;padding-right:70px}.smv-browse-marquee-track b{color:#62e5d2}@keyframes smvBrowseTicker{from{transform:translateX(0)}to{transform:translateX(-50%)}}
      .venue-filter-shell{position:sticky;top:88px;max-height:none!important;overflow:visible!important;padding:0!important;border:1px solid rgba(82,218,198,.22);border-radius:20px;background:linear-gradient(180deg,#0a3832,#062722 62%,#041c19);box-shadow:0 20px 48px rgba(0,0,0,.27),inset 0 1px 0 rgba(255,255,255,.035);color:#dff3ee}
      .smv-filter-clear-zone{padding:12px;border-bottom:1px solid rgba(255,255,255,.07)}.smv-filter-clear-zone.bottom{border-top:1px solid rgba(255,255,255,.07);border-bottom:0}.smv-filter-clear-btn{width:100%;min-height:38px;border:1px solid rgba(241,205,109,.34);border-radius:10px;background:linear-gradient(135deg,rgba(243,210,123,.14),rgba(243,200,75,.07));color:#f4d77f;font:inherit;font-size:11px;font-weight:950;cursor:pointer}
      .smv-filter-box{padding:0 14px 14px;border-bottom:1px solid rgba(255,255,255,.07)}.smv-filter-box:last-of-type{border-bottom:0}.smv-filter-title{margin:0 -14px 11px;padding:11px 14px;background:linear-gradient(90deg,#116458,#0a403a);color:#f4d986;font-size:11.5px;font-weight:950;letter-spacing:.11em;text-transform:uppercase}.smv-filter-list{display:grid;gap:4px}.smv-filter-choice{display:flex;align-items:center;justify-content:space-between;gap:8px;width:100%;min-height:34px;padding:5px 8px;border:1px solid transparent;border-radius:9px;background:transparent;color:#d3e8e4;font:inherit;font-size:12.5px;line-height:1.25;text-align:left;cursor:pointer}.smv-filter-choice:hover{background:rgba(71,213,192,.09);border-color:rgba(71,213,192,.14);color:#fff}.smv-filter-choice.active{background:linear-gradient(90deg,rgba(45,204,181,.2),rgba(45,204,181,.08));border-color:rgba(69,220,197,.3);color:#79f1de;font-weight:950}.smv-filter-choice b{color:#efd27b;font-size:11px}.smv-filter-subsearch{width:100%;height:39px;margin:0 0 9px;padding:0 10px;border:1px solid rgba(91,218,200,.2);border-radius:9px;background:#073b35;color:#f2fffc;font:inherit;font-size:12px;outline:none}.smv-filter-subsearch::placeholder{color:#8eb8b0}
      .smv-result-bar{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-bottom:11px;padding:11px 14px;border:1px solid rgba(94,226,207,.15);border-radius:12px;background:linear-gradient(135deg,rgba(17,74,66,.62),rgba(7,43,39,.68));color:#c9dfda;font-size:12px;font-weight:850}.smv-result-bar strong{color:#f5d986}.smv-clear{min-height:35px;padding:0 11px;border:1px solid rgba(235,199,101,.3);border-radius:9px;background:rgba(235,199,101,.08);color:#f3d47c;font:inherit;font-size:11px;font-weight:950;cursor:pointer}
      .venue-card{cursor:pointer}.smv-fit-note{margin:9px 0 0;padding:8px 10px;border-left:3px solid #2dd2bd;border-radius:8px;background:rgba(45,210,189,.07);color:#bfe2dc;font-size:10px;font-weight:850;line-height:1.45}.smv-fit-note b{color:#f3d984}.smv-venue-tools{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:9px}.smv-tool-btn{min-height:37px;border:1px solid rgba(109,231,211,.16);border-radius:9px;background:rgba(255,255,255,.025);color:#bfd7d3;font:inherit;font-size:9.5px;font-weight:900;cursor:pointer}.smv-tool-btn.active{border-color:rgba(243,200,75,.4);background:rgba(243,200,75,.08);color:#f4d883}.smv-market-bar{position:fixed;z-index:9990;left:50%;bottom:16px;transform:translateX(-50%);width:min(760px,calc(100% - 24px));display:flex;align-items:center;justify-content:space-between;gap:12px;padding:11px 14px;border:1px solid rgba(243,200,75,.28);border-radius:15px;background:rgba(3,24,23,.96);box-shadow:0 18px 50px rgba(0,0,0,.35);color:#dbeeea}.smv-market-bar[hidden]{display:none!important}.smv-market-bar button{min-height:36px;padding:0 11px;border:1px solid rgba(109,231,211,.18);border-radius:8px;background:rgba(255,255,255,.04);color:#d9efeb;font-size:9.5px;font-weight:900;cursor:pointer}.smv-market-bar button.primary{border:0;background:linear-gradient(135deg,#f1d476,#c89b36);color:#17352f}.smv-compare-link{display:flex;align-items:center;justify-content:center;min-height:38px;margin-top:12px;border-radius:9px;background:linear-gradient(135deg,#f1d476,#c89b36);color:#17352f!important;font-size:10px;font-weight:950;text-decoration:none}
      .smv-overlay{position:fixed;z-index:10020;inset:0;display:grid;place-items:center;padding:18px;background:rgba(0,16,15,.76);backdrop-filter:blur(8px)}.smv-overlay[hidden]{display:none!important}.smv-modal{width:min(900px,100%);max-height:88vh;overflow:auto;padding:20px;border:1px solid rgba(109,231,211,.18);border-radius:20px;background:#071f1d;color:#e9f7f4;box-shadow:0 28px 80px rgba(0,0,0,.45)}.smv-modal-head{display:flex;justify-content:space-between;gap:12px}.smv-close{width:36px;height:36px;border:0;border-radius:50%;background:rgba(255,255,255,.07);color:#fff;font-size:21px;cursor:pointer}.smv-compare-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:15px}.smv-compare-item{padding:13px;border:1px solid rgba(109,231,211,.12);border-radius:12px;background:rgba(255,255,255,.025)}.smv-compare-item b{display:block;margin-top:8px;color:#f2d179;font-size:8px}.smv-empty{display:none;padding:24px;border:1px dashed rgba(109,231,211,.2);border-radius:14px;color:#97bdb6;text-align:center}
      @media(max-width:1000px){.smv-browse-top-inner{grid-template-columns:1fr 1fr}.smv-browse-top input{grid-column:1/-1;grid-row:1}.venue-filter-shell{position:static}.smv-filter-list{grid-template-columns:repeat(2,minmax(0,1fr))}.smv-compare-grid{grid-template-columns:1fr}}
      @media(max-width:620px){.smv-browse-top-inner{width:min(100% - 18px,1460px);grid-template-columns:1fr}.smv-browse-top input,.smv-browse-top select,.smv-browse-top button{grid-column:1}.smv-filter-list{grid-template-columns:1fr}.smv-result-bar{align-items:flex-start;flex-direction:column}.smv-filter-choice{font-size:12px}}
    `;document.head.appendChild(s)
  }

  function installTopSearch(){
    if(document.getElementById("smvBrowseTop"))return;
    const header=document.querySelector(".page-header");if(!header)return;
    const bar=document.createElement("div");bar.id="smvBrowseTop";bar.className="smv-browse-top";bar.innerHTML='<div class="smv-browse-top-inner"><select id="smvBrowseCity"><option value="">All Delhi NCR</option></select><input id="smvBrowseSearch" type="search" placeholder="Search venue, category, locality or occasion"><select id="smvBrowseSort"><option value="recommended">Recommended</option><option value="price-low">Price: Low to High</option><option value="capacity-high">Capacity: High to Low</option><option value="name">Name: A–Z</option></select><button id="smvBrowseFind" type="button">Search Venues →</button></div><div class="smv-browse-marquee"><div class="smv-browse-marquee-track"><span>✦ <b>No commission from venues</b> · Verified venue partners · Smart matching · Free venue discovery</span><span>✦ <b>No commission from venues</b> · Verified venue partners · Smart matching · Free venue discovery</span></div></div>';header.insertAdjacentElement("afterend",bar)
  }

  function choice(label,value,count,cat){return `<button type="button" class="smv-filter-choice" data-category="${cat}" data-value="${escapeHtml(value)}"><span>${escapeHtml(label)}</span><b>${count}</b></button>`}
  function budgetLabel(p){return p<=1000?BUDGET_ORDER[0]:p<=1500?BUDGET_ORDER[1]:p<=2000?BUDGET_ORDER[2]:p<=3000?BUDGET_ORDER[3]:BUDGET_ORDER[4]}
  function clearAll(){Object.assign(state,{q:"",city:"",type:"",location:"",food:"",occasion:"",capacity:"",budget:"",more:"",sort:"recommended"});const q=document.getElementById("smvBrowseSearch"),c=document.getElementById("smvBrowseCity"),s=document.getElementById("smvBrowseSort");if(q)q.value="";if(c)c.value="";if(s)s.value="recommended";shell?.querySelectorAll("[data-filter-search]").forEach(i=>i.value="");render()}

  function buildFilters(){
    const maps={type:new Map(),location:new Map(),food:new Map(),occasion:new Map(),capacity:new Map(),budget:new Map(),more:new Map()},inc=(m,k)=>{if(k)m.set(k,(m.get(k)||0)+1)};
    venues.forEach(v=>{inc(maps.type,clean(v.venue_type)||"Venue");inc(maps.location,clean(v.city));inc(maps.location,clean(v.area));eventTypes(v).forEach(e=>inc(maps.occasion,e));inc(maps.capacity,capBucket(Number(v.capacity_max||v.capacity_min||0)));if(v.food_veg)inc(maps.food,"Vegetarian");if(v.food_non_veg)inc(maps.food,"Non-Vegetarian");if(v.parking_available)inc(maps.more,"Parking");if(v.rooms_available)inc(maps.more,"Rooms");if(v.catering_available)inc(maps.more,"Catering");if(v.decoration_available)inc(maps.more,"Decoration");const p=Number(v.price_min_per_person||0);if(p)inc(maps.budget,budgetLabel(p))});
    const ordered=(cat,map)=>cat==="capacity"?CAPACITY_ORDER.filter(x=>map.has(x)).map(x=>[x,map.get(x)]):cat==="budget"?BUDGET_ORDER.filter(x=>map.has(x)).map(x=>[x,map.get(x)]):cat==="food"?["Vegetarian","Non-Vegetarian"].filter(x=>map.has(x)).map(x=>[x,map.get(x)]):[...map.entries()].sort((a,b)=>a[0].localeCompare(b[0],undefined,{numeric:true,sensitivity:"base"}));
    const box=(title,cat,searchable=false)=>`<section class="smv-filter-box"><div class="smv-filter-title">${title}</div>${searchable?`<input class="smv-filter-subsearch" data-filter-search="${cat}" placeholder="Search ${title.toLowerCase()}">`:""}<div class="smv-filter-list" data-list="${cat}">${choice("All","",venues.length,cat)}${ordered(cat,maps[cat]).map(([x,c])=>choice(x,x,c,cat)).join("")}</div></section>`;
    ["Wedding","Engagement","Reception","Birthday","Anniversary","Corporate Event","Party"].forEach(e=>{if(!maps.occasion.has(e))maps.occasion.set(e,0)});
    const clearZone=position=>`<div class="smv-filter-clear-zone ${position}"><button type="button" class="smv-filter-clear-btn" data-clear-filters>Clear All Filters</button></div>`;
    shell.innerHTML=clearZone("top")+box("VENUES","type")+box("LOCATION","location",true)+box("MEAL / FOOD","food")+box("OCCASION","occasion",true)+'<p class="smv-filter-note">Counts show venue-listed event support. A zero means support has not been confirmed in current listings.</p>'+box("VENUE CAPACITY","capacity")+box("BUDGET / PERSON","budget")+box("MORE FILTERS","more")+clearZone("bottom");
    shell.addEventListener("click",e=>{if(e.target.closest("[data-clear-filters]")){clearAll();return}const b=e.target.closest(".smv-filter-choice");if(!b)return;state[b.dataset.category]=b.dataset.value||"";render()});
    shell.addEventListener("input",e=>{const i=e.target.closest("[data-filter-search]");if(!i)return;const t=normal(i.value),cat=i.dataset.filterSearch;shell.querySelectorAll(`[data-list="${cat}"] .smv-filter-choice`).forEach(b=>b.style.display=!t||normal(b.textContent).includes(t)?"":"none")});
    const city=document.getElementById("smvBrowseCity");city.innerHTML='<option value="">All Delhi NCR</option>'+[...new Set(venues.map(v=>clean(v.city)).filter(Boolean))].sort((a,b)=>a.localeCompare(b)).map(x=>`<option value="${escapeHtml(x)}">${escapeHtml(x)}</option>`).join("");if(state.city){const match=[...city.options].find(o=>normal(o.value)===normal(state.city)||normal(o.value).includes(normal(state.city))||normal(state.city).includes(normal(o.value)));if(match)city.value=match.value}
    document.getElementById("smvBrowseSearch").value=params.get("q")||"";
    document.getElementById("smvBrowseFind")?.addEventListener("click",()=>{state.q=normal(document.getElementById("smvBrowseSearch")?.value);state.city=clean(document.getElementById("smvBrowseCity")?.value);state.sort=clean(document.getElementById("smvBrowseSort")?.value)||"recommended";render()});
    document.getElementById("smvBrowseSearch")?.addEventListener("keydown",e=>{if(e.key==="Enter"){e.preventDefault();document.getElementById("smvBrowseFind")?.click()}});document.getElementById("smvBrowseCity")?.addEventListener("change",()=>{state.city=clean(document.getElementById("smvBrowseCity")?.value);render()});document.getElementById("smvBrowseSort")?.addEventListener("change",()=>{state.sort=clean(document.getElementById("smvBrowseSort")?.value);render()});
  }

  function matches(v){const location=[clean(v.area),clean(v.city)].filter(Boolean);const hay=[clean(v.venue_name),clean(v.venue_type),...location,eventTypes(v).join(" ")].join(" ").toLowerCase();if(state.q&&!hay.includes(state.q))return false;if(state.city&&normal(v.city)!==normal(state.city))return false;if(state.type&&clean(v.venue_type)!==state.type)return false;if(state.location&&!location.some(x=>normal(x)===normal(state.location)))return false;if(state.food==="Vegetarian"&&v.food_veg!==true)return false;if(state.food==="Non-Vegetarian"&&v.food_non_veg!==true)return false;if(state.occasion&&!eventTypes(v).some(e=>normal(e).includes(normal(state.occasion))||normal(state.occasion).includes(normal(e))))return false;if(state.capacity&&capBucket(Number(v.capacity_max||v.capacity_min||0))!==state.capacity)return false;if(state.budget){const p=Number(v.price_min_per_person||0);if(!p||budgetLabel(p)!==state.budget)return false}if(state.more==="Parking"&&v.parking_available!==true)return false;if(state.more==="Rooms"&&v.rooms_available!==true)return false;if(state.more==="Catering"&&v.catering_available!==true)return false;if(state.more==="Decoration"&&v.decoration_available!==true)return false;return true}

  function render(){
    let rows=venues.filter(matches);if(state.sort==="price-low")rows.sort((a,b)=>(Number(a.price_min_per_person)||999999)-(Number(b.price_min_per_person)||999999));else if(state.sort==="capacity-high")rows.sort((a,b)=>Number(b.capacity_max||b.capacity_min||0)-Number(a.capacity_max||a.capacity_min||0));else if(state.sort==="name")rows.sort((a,b)=>clean(a.venue_name).localeCompare(clean(b.venue_name)));
    let bar=document.querySelector(".smv-result-bar");if(!bar){bar=document.createElement("div");bar.className="smv-result-bar";grid.parentNode.insertBefore(bar,grid)}bar.innerHTML=`<span><strong>${rows.length}</strong> of ${venues.length} verified venues shown</span><button class="smv-clear" type="button">Clear All Filters</button>`;bar.querySelector(".smv-clear")?.addEventListener("click",clearAll);
    shell.querySelectorAll(".smv-filter-choice").forEach(b=>b.classList.toggle("active",state[b.dataset.category]===b.dataset.value));
    let empty=document.querySelector(".smv-empty");if(!empty){empty=document.createElement("div");empty.className="smv-empty";empty.textContent=state.occasion?"No venues have confirmed this event type in their listing yet. Clear this filter to browse all venues, or send an enquiry so our team can confirm suitability.":"No matching venues found. Try another filter or clear all filters.";grid.after(empty)}empty.style.display=rows.length?"none":"block";
    const fit=fitMessage();
    grid.innerHTML=rows.map(v=>{const id=String(v.id||""),href=`venue.html?id=${encodeURIComponent(id)}&pv=20260922-signature`,cover=safeUrl(v.cover_image_url),name=clean(v.venue_name)||"Venue Partner",loc=escapeHtml(publicLocation(v)),feat=features(v),short=shortlist.includes(id),comp=compare.includes(id);return `<article class="venue-card" data-profile-url="${escapeHtml(href)}" tabindex="0"><div class="venue-card-media">${cover?`<img src="${escapeHtml(cover)}" alt="${escapeHtml(name)} venue" loading="lazy" decoding="async">`:'<div class="venue-card-image-fallback">🏨</div>'}<div class="venue-card-top"><span class="venue-type">${escapeHtml(v.venue_type||"Venue")}</span><span class="verified">✓ Verified</span></div></div><div class="venue-card-body"><h2>${escapeHtml(name)}</h2><p class="venue-location">⌖ ${loc}</p><div class="venue-facts"><div class="venue-fact">${escapeHtml(capacityText(v))}</div><div class="venue-fact">${escapeHtml(priceText(v))}</div></div><div class="venue-feature-list">${feat.length?feat.slice(0,5).map(x=>`<span>✓ ${escapeHtml(x)}</span>`).join(""):"<span>Details on request</span>"}</div><p class="smv-fit-note"><b>Why it fits:</b> ${escapeHtml(fit)}</p><p class="venue-description">${escapeHtml(clean(v.description).slice(0,150)||"Ask our team for availability, packages and venue details.")}</p><div class="venue-actions"><a class="button button-primary" href="${href}">View Venue</a><a class="button button-secondary" href="${href}&quote=1">Check Availability</a></div><div class="smv-venue-tools"><button class="smv-tool-btn ${short?"active":""}" data-shortlist="${escapeHtml(id)}" type="button">${short?"✓ Shortlisted":"♡ Shortlist"}</button><button class="smv-tool-btn ${comp?"active":""}" data-compare="${escapeHtml(id)}" type="button">${comp?"✓ Comparing":"Compare"}</button></div></div></article>`}).join("");updateBar()
  }

  function updateBar(){let bar=document.getElementById("smvMarketBar");if(!bar){bar=document.createElement("div");bar.id="smvMarketBar";bar.className="smv-market-bar";document.body.appendChild(bar)}const selected=[...new Set([...shortlist,...compare])];bar.hidden=!selected.length;bar.innerHTML=`<strong>${selected.length} venue${selected.length===1?"":"s"} selected</strong><div><button id="smvCompareBtn" type="button">Compare</button><button class="primary" id="smvClearSelected" type="button">Clear</button></div>`;bar.querySelector("#smvCompareBtn")?.addEventListener("click",openCompare);bar.querySelector("#smvClearSelected")?.addEventListener("click",()=>{shortlist=[];compare=[];saveIds(SHORTLIST_KEY,shortlist);saveIds(COMPARE_KEY,compare);render()})}
  function openCompare(){const rows=compare.map(id=>venues.find(v=>String(v.id)===id)).filter(Boolean);if(rows.length<2){alert("Select at least 2 venues to compare.");return}track("compare_venues",{venue_count:rows.length});let o=document.getElementById("smvCompareOverlay");if(!o){o=document.createElement("div");o.id="smvCompareOverlay";o.className="smv-overlay";document.body.appendChild(o)}o.innerHTML=`<section class="smv-modal"><div class="smv-modal-head"><div><h2>Compare selected venues</h2><p>Only verified, published venue information is compared.</p></div><button class="smv-close" type="button">×</button></div><div class="smv-compare-grid">${rows.map(v=>`<article class="smv-compare-item"><h3>${escapeHtml(v.venue_name||"Venue")}</h3><b>LOCATION</b>${escapeHtml(publicLocation(v))}<b>CAPACITY</b>${escapeHtml(capacityText(v))}<b>PRICE</b>${escapeHtml(priceText(v))}<b>TYPE</b>${escapeHtml(v.venue_type||"Venue")}<b>FOOD & FACILITIES</b>${escapeHtml(features(v).join(" · ")||"On request")}<a class="smv-compare-link" href="venue.html?id=${encodeURIComponent(v.id)}&pv=20260922-signature&quote=1">Check Availability</a></article>`).join("")}</div></section>`;o.hidden=false;o.querySelector(".smv-close")?.addEventListener("click",()=>o.hidden=true);o.addEventListener("click",e=>{if(e.target===o)o.hidden=true},{once:true})}

  grid?.addEventListener("click",e=>{const s=e.target.closest("[data-shortlist]");if(s){e.preventDefault();e.stopPropagation();const id=s.dataset.shortlist,adding=!shortlist.includes(id);shortlist=adding?[...shortlist,id].slice(-8):shortlist.filter(x=>x!==id);saveIds(SHORTLIST_KEY,shortlist);track(adding?"shortlist_add":"shortlist_remove",{venue_id:id});render();return}const c=e.target.closest("[data-compare]");if(c){e.preventDefault();e.stopPropagation();const id=c.dataset.compare,adding=!compare.includes(id);if(!adding)compare=compare.filter(x=>x!==id);else if(compare.length<3)compare.push(id);else{alert("Compare supports up to 3 venues.");return}saveIds(COMPARE_KEY,compare);track(adding?"compare_add":"compare_remove",{venue_id:id});render();return}const availability=e.target.closest('a[href*="quote=1"]');if(availability)track("check_availability_click",{venue_url:availability.getAttribute("href")});if(e.target.closest("a,button,input,select,textarea,label"))return;const card=e.target.closest(".venue-card[data-profile-url]");if(card){track("venue_card_open",{venue_url:card.dataset.profileUrl});location.href=card.dataset.profileUrl}});

  async function load(){installStyles();installTopSearch();if(!grid||!shell){return}if(!client){grid.innerHTML='<div class="state-card"><h2>Venue search is temporarily unavailable</h2><p>Please refresh once or use the enquiry form while we reconnect the venue directory.</p></div>';return}let r=await client.rpc("smv_public_venues");if(r.error&&/function|schema cache/i.test(String(r.error.message||"")))r=await client.from("venues").select("id,venue_name,venue_type,description,city,area,capacity_min,capacity_max,price_min_per_person,price_max_per_person,food_veg,food_non_veg,parking_available,rooms_available,catering_available,decoration_available,cover_image_url,featured,event_types").eq("venue_status","approved").eq("verification_status","verified").eq("public_listing_enabled",true).order("featured",{ascending:false}).order("venue_name",{ascending:true});if(r.error){grid.innerHTML='<div class="state-card"><h2>Venue listings are being updated</h2><p>Please try again shortly.</p></div>';return}venues=(Array.isArray(r.data)?r.data:[]).map(x=>x?.venue||x).filter(Boolean);try{buildFilters();render()}catch(error){console.error("Venue render error:",error);state.q="";state.city="";state.type="";state.location="";state.food="";state.occasion="";state.capacity="";state.budget="";state.more="";state.sort="recommended";try{render()}catch(secondError){console.error("Venue fallback render error:",secondError);grid.innerHTML='<div class="state-card"><h2>We could not apply those filters</h2><p><a href="venues.html">Show all venues</a> or change the search filters.</p></div>'}}}
  load();
})();

