(function(){
  "use strict";
  const SUPABASE_URL="https://uajqwyoqbbswkfiwosyw.supabase.co";
  const SUPABASE_ANON_KEY="sb_publishable_hfiuO4ZRn4VZmEkrN2RV-A_lZX_R3z7";
  const SHORTLIST_KEY="smv_venue_shortlist_v2",COMPARE_KEY="smv_venue_compare_v2";
  const client=window.supabase?.createClient(SUPABASE_URL,SUPABASE_ANON_KEY,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});
  const grid=document.getElementById("venueGrid"),shell=document.querySelector(".venue-filter-shell"),params=new URLSearchParams(location.search);
  let venues=[],shortlist=readIds(SHORTLIST_KEY),compare=readIds(COMPARE_KEY).slice(0,3);
  const state={q:String(params.get("q")||"").trim().toLowerCase(),city:String(params.get("city")||params.get("location")||"").trim(),type:"",location:"",food:"",occasion:"",capacity:"",budget:"",more:"",sort:"recommended"};
  const clean=v=>String(v==null?"":v).trim(),normal=v=>clean(v).toLowerCase(),escapeHtml=v=>String(v??"").replace(/[&<>'\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'\"':"&quot;"})[c]);
  const safeUrl=v=>{try{const u=new URL(String(v||""));return["http:","https:"].includes(u.protocol)?u.href:""}catch(_){return""}};
  const eventTypes=v=>{const raw=v.event_types||v.events||v.suitable_events||[];return Array.isArray(raw)?raw.map(String).map(clean).filter(Boolean):String(raw||"").split(/[,|]/).map(clean).filter(Boolean)};
  const money=v=>!v?null:new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(Number(v));
  const capacityText=v=>{const a=Number(v.capacity_min||0),b=Number(v.capacity_max||0);return a&&b?`${a}–${b} guests`:b?`Up to ${b} guests`:a?`${a}+ guests`:"On request"};
  const priceText=v=>{const a=money(v.price_min_per_person),b=money(v.price_max_per_person);return a&&b?`${a}–${b}/person`:a?`${a}+/person`:b?`Up to ${b}/person`:"Quote on request"};
  const features=v=>{const a=[];if(v.food_veg)a.push("Vegetarian");if(v.food_non_veg)a.push("Non-Vegetarian");if(v.parking_available)a.push("Parking");if(v.rooms_available)a.push("Rooms");if(v.catering_available)a.push("Catering");if(v.decoration_available)a.push("Decoration");return a};
  function readIds(k){try{const x=JSON.parse(localStorage.getItem(k)||"[]");return Array.isArray(x)?x.map(String):[]}catch(_){return[]}}
  function saveIds(k,x){try{localStorage.setItem(k,JSON.stringify(x))}catch(_){}}
  function capBucket(n){if(n<50)return"Less than 50";if(n<100)return"50–99";if(n<200)return"100–199";if(n<300)return"200–299";if(n<500)return"300–499";if(n<700)return"500–699";if(n<1000)return"700–999";return"1000+"}
  const CAPACITY_ORDER=["Less than 50","50–99","100–199","200–299","300–499","500–699","700–999","1000+"];
  const BUDGET_ORDER=["Up to ₹1,000","₹1,001–1,500","₹1,501–2,000","₹2,001–3,000","₹3,000+"];

  function installStyles(){
    if(document.getElementById("smvBrowsePremiumFilters"))return;
    const s=document.createElement("style");s.id="smvBrowsePremiumFilters";s.textContent=`
      .smv-browse-top{position:relative;z-index:20;border-bottom:1px solid rgba(93,223,204,.16);background:linear-gradient(100deg,#062d29,#0b4a42 55%,#062d29);box-shadow:0 10px 28px rgba(0,0,0,.18)}
      .smv-browse-top-inner{width:min(1460px,calc(100% - 34px));margin:auto;display:grid;grid-template-columns:210px minmax(0,1fr) 150px 160px;gap:10px;padding:10px 0}.smv-browse-top select,.smv-browse-top input{min-height:44px;width:100%;border:1px solid rgba(109,231,211,.23);border-radius:11px;background:#073b35;color:#effffb;padding:0 12px;font:inherit;font-size:11.5px;font-weight:800;outline:none}.smv-browse-top input::placeholder{color:#8db7af}.smv-browse-top button{min-height:44px;border:1px solid rgba(240,205,112,.34);border-radius:11px;background:linear-gradient(135deg,#f2d47c,#c69a36);color:#17382f;font:inherit;font-size:10.5px;font-weight:950;cursor:pointer}
      .venue-filter-shell{position:sticky;top:88px;max-height:none!important;overflow:visible!important;padding:0!important;border:1px solid rgba(82,218,198,.2);border-radius:20px;background:linear-gradient(180deg,#082f2b,#051f1d);box-shadow:0 18px 45px rgba(0,0,0,.24);color:#d8f0eb}
      .smv-filter-box{padding:0 12px 12px;border-bottom:1px solid rgba(255,255,255,.07)}.smv-filter-box:last-child{border-bottom:0}.smv-filter-title{margin:0 -12px 10px;padding:10px 12px;background:linear-gradient(90deg,#0e5a50,#0a403a);color:#f2d178;font-size:9px;font-weight:950;letter-spacing:.12em;text-transform:uppercase}.smv-filter-box:first-child .smv-filter-title{border-radius:19px 19px 0 0}.smv-filter-list{display:grid;gap:3px}.smv-filter-choice{display:flex;align-items:center;justify-content:space-between;gap:8px;width:100%;min-height:29px;padding:3px 7px;border:1px solid transparent;border-radius:8px;background:transparent;color:#c2ddd7;font:inherit;font-size:9.5px;text-align:left;cursor:pointer}.smv-filter-choice:hover{background:rgba(71,213,192,.08);border-color:rgba(71,213,192,.12);color:#fff}.smv-filter-choice.active{background:linear-gradient(90deg,rgba(45,204,181,.18),rgba(45,204,181,.08));border-color:rgba(69,220,197,.28);color:#69ead7;font-weight:950}.smv-filter-choice b{color:#e8c76e;font-size:8.5px}.smv-filter-subsearch{width:100%;height:34px;margin:0 0 8px;padding:0 9px;border:1px solid rgba(91,218,200,.16);border-radius:8px;background:#073b35;color:#e9fbf7;font:inherit;font-size:9.5px;outline:none}.smv-filter-subsearch::placeholder{color:#78a79f}
      .smv-result-bar{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-bottom:11px;padding:10px 13px;border:1px solid rgba(94,226,207,.14);border-radius:12px;background:linear-gradient(135deg,rgba(17,74,66,.55),rgba(7,43,39,.6));color:#b9d5d0;font-size:10px;font-weight:850}.smv-result-bar strong{color:#f2d179}.smv-clear{min-height:32px;padding:0 10px;border:1px solid rgba(235,199,101,.28);border-radius:8px;background:rgba(235,199,101,.07);color:#f0ce72;font:inherit;font-size:9px;font-weight:950;cursor:pointer}
      .venue-card{cursor:pointer}.smv-venue-tools{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:9px}.smv-tool-btn{min-height:37px;border:1px solid rgba(109,231,211,.16);border-radius:9px;background:rgba(255,255,255,.025);color:#bfd7d3;font:inherit;font-size:9.5px;font-weight:900;cursor:pointer}.smv-tool-btn.active{border-color:rgba(243,200,75,.4);background:rgba(243,200,75,.08);color:#f4d883}.smv-market-bar{position:fixed;z-index:9990;left:50%;bottom:16px;transform:translateX(-50%);width:min(760px,calc(100% - 24px));display:flex;align-items:center;justify-content:space-between;gap:12px;padding:11px 14px;border:1px solid rgba(243,200,75,.28);border-radius:15px;background:rgba(3,24,23,.96);box-shadow:0 18px 50px rgba(0,0,0,.35);color:#dbeeea}.smv-market-bar[hidden]{display:none!important}.smv-market-bar button{min-height:36px;padding:0 11px;border:1px solid rgba(109,231,211,.18);border-radius:8px;background:rgba(255,255,255,.04);color:#d9efeb;font-size:9.5px;font-weight:900;cursor:pointer}.smv-market-bar button.primary{border:0;background:linear-gradient(135deg,#f1d476,#c89b36);color:#17352f}
      .smv-overlay{position:fixed;z-index:10020;inset:0;display:grid;place-items:center;padding:18px;background:rgba(0,16,15,.76);backdrop-filter:blur(8px)}.smv-overlay[hidden]{display:none!important}.smv-modal{width:min(900px,100%);max-height:88vh;overflow:auto;padding:20px;border:1px solid rgba(109,231,211,.18);border-radius:20px;background:#071f1d;color:#e9f7f4;box-shadow:0 28px 80px rgba(0,0,0,.45)}.smv-modal-head{display:flex;justify-content:space-between;gap:12px}.smv-close{width:36px;height:36px;border:0;border-radius:50%;background:rgba(255,255,255,.07);color:#fff;font-size:21px;cursor:pointer}.smv-compare-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:15px}.smv-compare-item{padding:13px;border:1px solid rgba(109,231,211,.12);border-radius:12px;background:rgba(255,255,255,.025)}.smv-compare-item b{display:block;margin-top:8px;color:#f2d179;font-size:8px}.smv-empty{display:none;padding:24px;border:1px dashed rgba(109,231,211,.2);border-radius:14px;color:#97bdb6;text-align:center}
      @media(max-width:1000px){.smv-browse-top-inner{grid-template-columns:1fr 1fr}.smv-browse-top input{grid-column:1/-1;grid-row:1}.venue-filter-shell{position:static}.smv-filter-list{grid-template-columns:repeat(2,minmax(0,1fr))}.smv-compare-grid{grid-template-columns:1fr}}
      @media(max-width:620px){.smv-browse-top-inner{width:min(100% - 18px,1460px);grid-template-columns:1fr}.smv-browse-top input,.smv-browse-top select,.smv-browse-top button{grid-column:1}.smv-filter-list{grid-template-columns:1fr}.smv-result-bar{align-items:flex-start;flex-direction:column}}
    `;document.head.appendChild(s)
  }

  function installTopSearch(){
    if(document.getElementById("smvBrowseTop"))return;
    const header=document.querySelector(".page-header");if(!header)return;
    const bar=document.createElement("div");bar.id="smvBrowseTop";bar.className="smv-browse-top";bar.innerHTML='<div class="smv-browse-top-inner"><select id="smvBrowseCity"><option value="">All Delhi NCR</option></select><input id="smvBrowseSearch" type="search" placeholder="Search venue, category, locality or occasion"><select id="smvBrowseSort"><option value="recommended">Recommended</option><option value="price-low">Price: Low to High</option><option value="capacity-high">Capacity: High to Low</option><option value="name">Name: A–Z</option></select><button id="smvBrowseFind" type="button">Search Venues →</button></div>';header.insertAdjacentElement("afterend",bar)
  }

  function choice(label,value,count,cat){return `<button type="button" class="smv-filter-choice" data-category="${cat}" data-value="${escapeHtml(value)}"><span>${escapeHtml(label)}</span><b>${count}</b></button>`}
  function budgetLabel(p){return p<=1000?BUDGET_ORDER[0]:p<=1500?BUDGET_ORDER[1]:p<=2000?BUDGET_ORDER[2]:p<=3000?BUDGET_ORDER[3]:BUDGET_ORDER[4]}
  function buildFilters(){
    const maps={type:new Map(),location:new Map(),food:new Map(),occasion:new Map(),capacity:new Map(),budget:new Map(),more:new Map()},inc=(m,k)=>{if(k)m.set(k,(m.get(k)||0)+1)};
    venues.forEach(v=>{inc(maps.type,clean(v.venue_type)||"Venue");inc(maps.location,clean(v.city));inc(maps.location,clean(v.area));eventTypes(v).forEach(e=>inc(maps.occasion,e));inc(maps.capacity,capBucket(Number(v.capacity_max||v.capacity_min||0)));if(v.food_veg)inc(maps.food,"Vegetarian");if(v.food_non_veg)inc(maps.food,"Non-Vegetarian");if(v.parking_available)inc(maps.more,"Parking");if(v.rooms_available)inc(maps.more,"Rooms");if(v.catering_available)inc(maps.more,"Catering");if(v.decoration_available)inc(maps.more,"Decoration");const p=Number(v.price_min_per_person||0);if(p)inc(maps.budget,budgetLabel(p))});
    const ordered=(cat,map)=>cat==="capacity"?CAPACITY_ORDER.filter(x=>map.has(x)).map(x=>[x,map.get(x)]):cat==="budget"?BUDGET_ORDER.filter(x=>map.has(x)).map(x=>[x,map.get(x)]):cat==="food"?["Vegetarian","Non-Vegetarian"].filter(x=>map.has(x)).map(x=>[x,map.get(x)]):[...map.entries()].sort((a,b)=>a[0].localeCompare(b[0],undefined,{numeric:true,sensitivity:"base"}));
    const box=(title,cat,searchable=false)=>`<section class="smv-filter-box"><div class="smv-filter-title">${title}</div>${searchable?`<input class="smv-filter-subsearch" data-filter-search="${cat}" placeholder="Search ${title.toLowerCase()}">`:""}<div class="smv-filter-list" data-list="${cat}">${choice("All","",venues.length,cat)}${ordered(cat,maps[cat]).map(([x,c])=>choice(x,x,c,cat)).join("")}</div></section>`;
    shell.innerHTML=box("VENUES","type")+box("LOCATION","location",true)+box("MEAL / FOOD","food")+box("OCCASION","occasion",true)+box("VENUE CAPACITY","capacity")+box("BUDGET / PERSON","budget")+box("MORE FILTERS","more");
    shell.addEventListener("click",e=>{const b=e.target.closest(".smv-filter-choice");if(!b)return;state[b.dataset.category]=b.dataset.value||"";render()});
    shell.addEventListener("input",e=>{const i=e.target.closest("[data-filter-search]");if(!i)return;const t=normal(i.value),cat=i.dataset.filterSearch;shell.querySelectorAll(`[data-list="${cat}"] .smv-filter-choice`).forEach(b=>b.style.display=!t||normal(b.textContent).includes(t)?"":"none")});
    const city=document.getElementById("smvBrowseCity");city.innerHTML='<option value="">All Delhi NCR</option>'+[...new Set(venues.map(v=>clean(v.city)).filter(Boolean))].sort((a,b)=>a.localeCompare(b)).map(x=>`<option value="${escapeHtml(x)}">${escapeHtml(x)}</option>`).join("");if(state.city){const match=[...city.options].find(o=>normal(o.value)===normal(state.city)||normal(o.value).includes(normal(state.city))||normal(state.city).includes(normal(o.value)));if(match)city.value=match.value}
    document.getElementById("smvBrowseSearch").value=params.get("q")||"";
    document.getElementById("smvBrowseFind")?.addEventListener("click",()=>{state.q=normal(document.getElementById("smvBrowseSearch")?.value);state.city=clean(document.getElementById("smvBrowseCity")?.value);state.sort=clean(document.getElementById("smvBrowseSort")?.value)||"recommended";render()});
    document.getElementById("smvBrowseSearch")?.addEventListener("keydown",e=>{if(e.key==="Enter"){e.preventDefault();document.getElementById("smvBrowseFind")?.click()}});
    document.getElementById("smvBrowseCity")?.addEventListener("change",()=>{state.city=clean(document.getElementById("smvBrowseCity")?.value);render()});
    document.getElementById("smvBrowseSort")?.addEventListener("change",()=>{state.sort=clean(document.getElementById("smvBrowseSort")?.value);render()});
  }

  function matches(v){const location=[clean(v.area),clean(v.city)].filter(Boolean);const hay=[clean(v.venue_name),clean(v.venue_type),...location,eventTypes(v).join(" ")].join(" ").toLowerCase();if(state.q&&!hay.includes(state.q))return false;if(state.city&&normal(v.city)!==normal(state.city))return false;if(state.type&&clean(v.venue_type)!==state.type)return false;if(state.location&&!location.some(x=>normal(x)===normal(state.location)))return false;if(state.food==="Vegetarian"&&v.food_veg!==true)return false;if(state.food==="Non-Vegetarian"&&v.food_non_veg!==true)return false;if(state.occasion&&!eventTypes(v).some(e=>normal(e).includes(normal(state.occasion))||normal(state.occasion).includes(normal(e))))return false;if(state.capacity&&capBucket(Number(v.capacity_max||v.capacity_min||0))!==state.capacity)return false;if(state.budget){const p=Number(v.price_min_per_person||0);if(!p||budgetLabel(p)!==state.budget)return false}if(state.more==="Parking"&&v.parking_available!==true)return false;if(state.more==="Rooms"&&v.rooms_available!==true)return false;if(state.more==="Catering"&&v.catering_available!==true)return false;if(state.more==="Decoration"&&v.decoration_available!==true)return false;return true}

  function render(){
    let rows=venues.filter(matches);if(state.sort==="price-low")rows.sort((a,b)=>(Number(a.price_min_per_person)||999999)-(Number(b.price_min_per_person)||999999));else if(state.sort==="capacity-high")rows.sort((a,b)=>Number(b.capacity_max||b.capacity_min||0)-Number(a.capacity_max||a.capacity_min||0));else if(state.sort==="name")rows.sort((a,b)=>clean(a.venue_name).localeCompare(clean(b.venue_name)));
    let bar=document.querySelector(".smv-result-bar");if(!bar){bar=document.createElement("div");bar.className="smv-result-bar";grid.parentNode.insertBefore(bar,grid)}bar.innerHTML=`<span><strong>${rows.length}</strong> of ${venues.length} verified venues shown</span><button class="smv-clear" type="button">Clear All Filters</button>`;bar.querySelector(".smv-clear")?.addEventListener("click",()=>{Object.assign(state,{q:"",city:"",type:"",location:"",food:"",occasion:"",capacity:"",budget:"",more:"",sort:"recommended"});document.getElementById("smvBrowseSearch").value="";document.getElementById("smvBrowseCity").value="";document.getElementById("smvBrowseSort").value="recommended";render()});
    shell.querySelectorAll(".smv-filter-choice").forEach(b=>b.classList.toggle("active",state[b.dataset.category]===b.dataset.value));
    let empty=document.querySelector(".smv-empty");if(!empty){empty=document.createElement("div");empty.className="smv-empty";empty.textContent="No matching venues found. Try another filter or clear all filters.";grid.after(empty)}empty.style.display=rows.length?"none":"block";
    grid.innerHTML=rows.map(v=>{const id=String(v.id||""),href=`venue.html?id=${encodeURIComponent(id)}`,cover=safeUrl(v.cover_image_url),name=clean(v.venue_name)||"Venue Partner",loc=[v.area,v.city].filter(Boolean).map(escapeHtml).join(", ")||"Location on request",feat=features(v),short=shortlist.includes(id),comp=compare.includes(id);return `<article class="venue-card" data-profile-url="${escapeHtml(href)}" tabindex="0"><div class="venue-card-media">${cover?`<img src="${escapeHtml(cover)}" alt="${escapeHtml(name)} venue" loading="lazy" decoding="async">`:'<div class="venue-card-image-fallback">🏨</div>'}<div class="venue-card-top"><span class="venue-type">${escapeHtml(v.venue_type||"Venue")}</span><span class="verified">✓ Verified</span></div></div><div class="venue-card-body"><h2>${escapeHtml(name)}</h2><p class="venue-location">⌖ ${loc}</p><div class="venue-facts"><div class="venue-fact">${escapeHtml(capacityText(v))}</div><div class="venue-fact">${escapeHtml(priceText(v))}</div></div><div class="venue-feature-list">${feat.length?feat.slice(0,5).map(x=>`<span>✓ ${escapeHtml(x)}</span>`).join(""):"<span>Details on request</span>"}</div><p class="venue-description">${escapeHtml(clean(v.description).slice(0,150)||"Ask our team for availability, packages and venue details.")}</p><div class="venue-actions"><a class="button button-primary" href="${href}">View Venue</a><a class="button button-secondary" href="${href}&quote=1">Check Availability</a></div><div class="smv-venue-tools"><button class="smv-tool-btn ${short?"active":""}" data-shortlist="${escapeHtml(id)}" type="button">${short?"✓ Shortlisted":"♡ Shortlist"}</button><button class="smv-tool-btn ${comp?"active":""}" data-compare="${escapeHtml(id)}" type="button">${comp?"✓ Comparing":"Compare"}</button></div></div></article>`}).join("");updateBar()
  }

  function updateBar(){let bar=document.getElementById("smvMarketBar");if(!bar){bar=document.createElement("div");bar.id="smvMarketBar";bar.className="smv-market-bar";document.body.appendChild(bar)}const selected=[...new Set([...shortlist,...compare])];bar.hidden=!selected.length;bar.innerHTML=`<strong>${selected.length} venue${selected.length===1?"":"s"} selected</strong><div><button id="smvCompareBtn" type="button">Compare</button><button class="primary" id="smvClearSelected" type="button">Clear</button></div>`;bar.querySelector("#smvCompareBtn")?.addEventListener("click",openCompare);bar.querySelector("#smvClearSelected")?.addEventListener("click",()=>{shortlist=[];compare=[];saveIds(SHORTLIST_KEY,shortlist);saveIds(COMPARE_KEY,compare);render()})}
  function openCompare(){const rows=compare.map(id=>venues.find(v=>String(v.id)===id)).filter(Boolean);if(rows.length<2){alert("Select at least 2 venues to compare.");return}let o=document.getElementById("smvCompareOverlay");if(!o){o=document.createElement("div");o.id="smvCompareOverlay";o.className="smv-overlay";document.body.appendChild(o)}o.innerHTML=`<section class="smv-modal"><div class="smv-modal-head"><div><h2>Compare selected venues</h2><p>Published venue details only.</p></div><button class="smv-close" type="button">×</button></div><div class="smv-compare-grid">${rows.map(v=>`<article class="smv-compare-item"><h3>${escapeHtml(v.venue_name||"Venue")}</h3><b>LOCATION</b>${escapeHtml([v.area,v.city].filter(Boolean).join(", ")||"On request")}<b>CAPACITY</b>${escapeHtml(capacityText(v))}<b>PRICE</b>${escapeHtml(priceText(v))}<b>TYPE</b>${escapeHtml(v.venue_type||"Venue")}<b>FACILITIES</b>${escapeHtml(features(v).join(" · ")||"On request")}</article>`).join("")}</div></section>`;o.hidden=false;o.querySelector(".smv-close")?.addEventListener("click",()=>o.hidden=true);o.addEventListener("click",e=>{if(e.target===o)o.hidden=true},{once:true})}

  grid?.addEventListener("click",e=>{const s=e.target.closest("[data-shortlist]");if(s){e.preventDefault();e.stopPropagation();const id=s.dataset.shortlist;shortlist=shortlist.includes(id)?shortlist.filter(x=>x!==id):[...shortlist,id].slice(-8);saveIds(SHORTLIST_KEY,shortlist);render();return}const c=e.target.closest("[data-compare]");if(c){e.preventDefault();e.stopPropagation();const id=c.dataset.compare;if(compare.includes(id))compare=compare.filter(x=>x!==id);else if(compare.length<3)compare.push(id);else{alert("Compare supports up to 3 venues.");return}saveIds(COMPARE_KEY,compare);render();return}if(e.target.closest("a,button,input,select,textarea,label"))return;const card=e.target.closest(".venue-card[data-profile-url]");if(card)location.href=card.dataset.profileUrl});

  async function load(){installStyles();installTopSearch();if(!grid||!shell||!client)return;let r=await client.rpc("smv_public_venues");if(r.error&&/function|schema cache/i.test(String(r.error.message||"")))r=await client.from("venues").select("id,venue_name,venue_type,description,city,area,capacity_min,capacity_max,price_min_per_person,price_max_per_person,food_veg,food_non_veg,parking_available,rooms_available,catering_available,decoration_available,cover_image_url,featured,event_types").eq("venue_status","approved").eq("verification_status","verified").eq("public_listing_enabled",true).order("featured",{ascending:false}).order("venue_name",{ascending:true});if(r.error){grid.innerHTML='<div class="state-card"><h2>Venue listings are being updated</h2><p>Please try again shortly.</p></div>';return}venues=(Array.isArray(r.data)?r.data:[]).map(x=>x?.venue||x).filter(Boolean);buildFilters();render()}
  load();
})();